name: Frontend CI/CD

# trigger on pushes and PRs to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run unit tests
        run: npm run test -- --coverage
        working-directory: ./frontend

      - name: Build production build
        run: npm run build
        working-directory: ./frontend

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Docker image
        run: |
          IMAGE=your-dockerhub-username/campus-frontend
          TAG=latest
          docker build -f frontend/Dockerfile -t $IMAGE:$TAG frontend
          docker push $IMAGE:$TAG
